// Image paths from public folder
export const IMAGES = {
  hero: '/hero_ghost_1787633688868.jpg',
  laptop: '/laptop_1787633700695.jpg',
  gpu: '/gpu_1787633713974.jpg',
  monitor: '/monitor_1787633728962.jpg',
  pc: '/pc_1787633742711.jpg',
  blueprint: '/blueprint_1787633759905.jpg',
  media1: '/media_1787635448546.jpg',
  media2: '/media_1787635454440.jpg',
  media3: '/media_1787635462982.jpg',
};

// Categories based on PCPoint inventory structure
export const CATEGORIES = [
  { id: 'all', name: 'ALL PRODUCTS', count: '32 Items', img: IMAGES.pc, tag: 'ALL' },
  { id: 'laptops', name: 'LAPTOPS', count: '14 Models', img: IMAGES.laptop, tag: 'LAPTOPS' },
  { id: 'gpus', name: 'GRAPHICS CARDS', count: '18 Units', img: IMAGES.gpu, tag: 'GRAPHICS CARDS' },
  { id: 'processors', name: 'PROCESSORS', count: '16 CPUs', img: IMAGES.pc, tag: 'PROCESSORS' },
  { id: 'motherboards', name: 'MOTHERBOARDS', count: '12 Boards', img: IMAGES.blueprint, tag: 'MOTHERBOARDS' },
  { id: 'coolers', name: 'COOLERS & AIO', count: '10 Coolers', img: IMAGES.media2, tag: 'COOLERS' },
  { id: 'storage', name: 'STORAGE & SSD', count: '15 Drives', img: IMAGES.media1, tag: 'STORAGE' },
  { id: 'monitors', name: 'MONITORS & DISPLAYS', count: '9 Displays', img: IMAGES.monitor, tag: 'MONITORS' },
  { id: 'peripherals', name: 'KEYBOARDS & AUDIO', count: '22 Peripherals', img: IMAGES.media3, tag: 'PERIPHERALS' },
];

export const BRANDS = [
  'Asus',
  'MSI',
  'Corsair',
  'Arctic',
  'Thermaltake',
  'Intel',
  'AMD',
  'Crucial',
  'Samsung',
  'Keychron',
  'Razer',
  'Addlink',
];

// Product catalog curated for PCPoint Market with official LKR pricing & Koko installments
export const PRODUCTS = [
  {
    id: 'lap-01',
    name: 'ASUS ROG Strix SCAR 18 (2024)',
    category: 'laptops',
    categoryName: 'GAMING LAPTOP',
    brand: 'Asus',
    badge: 'FLAGSHIP BEAST',
    price: 1350000,
    oldPrice: 1420000,
    inStock: true,
    rating: 4.9,
    reviewsCount: 38,
    warranty: '2 Years Asus Global Warranty',
    img: IMAGES.laptop,
    specs: 'Intel i9-14900HX // RTX 4090 16GB // 32GB DDR5 5600MHz // 2TB Gen4 SSD // 18" 2.5K 240Hz Nebula HDR',
    description: 'Dominate Windows 11 gaming with the 2024 ROG Strix SCAR 18. Equipped with an Intel Core i9-14900HX Processor and NVIDIA GeForce RTX 4090 Laptop GPU with max 175W TGP.',
    tags: ['RTX 4090', 'Intel i9', 'DDR5', '240Hz', 'Gaming'],
  },
  {
    id: 'lap-02',
    name: 'MSI Raider GE78 HX Smart Touch Edition',
    category: 'laptops',
    categoryName: 'GAMING LAPTOP',
    brand: 'MSI',
    badge: 'BEST SELLER',
    price: 985000,
    oldPrice: 1050000,
    inStock: true,
    rating: 4.8,
    reviewsCount: 29,
    warranty: '2 Years MSI Official Warranty',
    img: IMAGES.laptop,
    specs: 'Intel Core i9-14900HX // RTX 4080 12GB // 32GB DDR5 // 1TB NVMe // 17" QHD+ 240Hz OLED',
    description: 'Sky is the limit. Inspired by the discovery of black hole Sagittarius A, Raider GE78 HX once again makes the impossible possible with extreme computing capability.',
    tags: ['RTX 4080', 'Intel i9', 'DDR5', '240Hz'],
  },
  {
    id: 'lap-03',
    name: 'ASUS TUF Gaming A15 (2024)',
    category: 'laptops',
    categoryName: 'GAMING LAPTOP',
    brand: 'Asus',
    badge: 'VALUE CHAMPION',
    price: 385000,
    oldPrice: 410000,
    inStock: true,
    rating: 4.7,
    reviewsCount: 64,
    warranty: '2 Years Asus Warranty',
    img: IMAGES.laptop,
    specs: 'AMD Ryzen 7 8845HS // RTX 4060 8GB 140W // 16GB DDR5 // 1TB Gen4 SSD // 15.6" 144Hz FHD 100% sRGB',
    description: 'Geared for serious gaming and rocking a slick military-grade styling, the TUF Gaming A15 is a feature-packed Windows 11 gaming laptop with power to carry you to victory.',
    tags: ['RTX 4060', 'Ryzen 7', 'DDR5', '144Hz'],
  },
  {
    id: 'gpu-01',
    name: 'ASUS ROG Strix GeForce RTX 4090 OC White 24GB',
    category: 'gpus',
    categoryName: 'GRAPHICS CARD',
    brand: 'Asus',
    badge: 'GOD TIER',
    price: 895000,
    oldPrice: 940000,
    inStock: true,
    rating: 5.0,
    reviewsCount: 42,
    warranty: '3 Years Official Warranty',
    img: IMAGES.gpu,
    specs: '24GB GDDR6X // 384-bit // 16384 CUDA Cores // Axial-tech Fans // DLSS 3.5 & Frame Gen',
    description: 'The definitive gaming GPU. Powered by the ultra-efficient Ada Lovelace architecture and full ray tracing, the ROG Strix RTX 4090 delivers astronomical framerates in 4K resolution.',
    tags: ['RTX 4090', '24GB VRAM', 'DLSS 3.5', '4K Gaming'],
  },
  {
    id: 'gpu-02',
    name: 'MSI GeForce RTX 4070 Ti SUPER 16G GAMING X SLIM',
    category: 'gpus',
    categoryName: 'GRAPHICS CARD',
    brand: 'MSI',
    badge: 'POPULAR CHOICE',
    price: 365000,
    oldPrice: 389000,
    inStock: true,
    rating: 4.9,
    reviewsCount: 51,
    warranty: '3 Years Official Warranty',
    img: IMAGES.gpu,
    specs: '16GB GDDR6X // 256-bit // TRI FROZR 3 Thermal Design // TORX Fan 5.0 // Metal Backplate',
    description: 'The MSI GeForce RTX 4070 Ti SUPER delivers outstanding 1440p and 4K performance with 16GB VRAM, perfect for high refresh AAA gaming and generative AI workflows.',
    tags: ['RTX 4070 Ti Super', '16GB VRAM', 'DLSS 3.5', 'Tri Frozr'],
  },
  {
    id: 'gpu-03',
    name: 'MSI GeForce RTX 4060 VENTUS 2X Black 8G OC',
    category: 'gpus',
    categoryName: 'GRAPHICS CARD',
    brand: 'MSI',
    badge: 'BUDGET HERO',
    price: 135000,
    oldPrice: 145000,
    inStock: true,
    rating: 4.6,
    reviewsCount: 88,
    warranty: '3 Years Official Warranty',
    img: IMAGES.gpu,
    specs: '8GB GDDR6 // Dual Fan Thermal // Ray Tracing & DLSS 3 // Low Power 115W TDP',
    description: 'The essential GPU for 1080p esports and AAA high settings gaming. Exceptional power efficiency with dual TORX 4.0 cooling fans.',
    tags: ['RTX 4060', '8GB VRAM', 'DLSS 3', 'Budget'],
  },
  {
    id: 'cpu-01',
    name: 'Intel Core i9-14900K 24-Core Processor (PCPoint Special)',
    category: 'processors',
    categoryName: 'PROCESSOR',
    brand: 'Intel',
    badge: 'MAX PERFORMANCE',
    price: 215000,
    oldPrice: 235000,
    inStock: true,
    rating: 4.9,
    reviewsCount: 73,
    warranty: '3 Years Intel Warranty',
    img: IMAGES.pc,
    specs: '24 Cores (8P + 16E) // 32 Threads // Up to 6.0GHz Turbo Boost Max // LGA1700 // 36MB Cache',
    description: 'Break boundaries with Intel Core i9-14900K desktop processor. Unlocked for extreme overclocking, 6.0 GHz out of the box performance for unmatched gaming and productivity.',
    tags: ['Intel i9', '14th Gen', '6.0GHz', 'LGA1700'],
  },
  {
    id: 'cpu-02',
    name: 'AMD Ryzen 7 7800X3D 8-Core 3D V-Cache Processor',
    category: 'processors',
    categoryName: 'PROCESSOR',
    brand: 'AMD',
    badge: '#1 GAMING CPU',
    price: 168000,
    oldPrice: 179000,
    inStock: true,
    rating: 5.0,
    reviewsCount: 112,
    warranty: '3 Years AMD Warranty',
    img: IMAGES.pc,
    specs: '8 Cores // 16 Threads // 5.0GHz Max Boost // 104MB Combined Cache // AM5 Socket // 120W TDP',
    description: 'The undisputed champion of gaming CPUs. Features AMD 3D V-Cache technology for monstrous frame rates in the most demanding titles.',
    tags: ['Ryzen 7', '3D V-Cache', 'AM5', 'Gaming CPU'],
  },
  {
    id: 'cpu-03',
    name: 'Intel Core i5-14400F 10-Core Processor',
    category: 'processors',
    categoryName: 'PROCESSOR',
    brand: 'Intel',
    badge: 'BEST VALUE',
    price: 68500,
    oldPrice: 74000,
    inStock: true,
    rating: 4.7,
    reviewsCount: 95,
    warranty: '3 Years Intel Warranty',
    img: IMAGES.pc,
    specs: '10 Cores (6P + 4E) // 16 Threads // Up to 4.7GHz // 20MB Cache // LGA1700 // 65W TDP',
    description: 'Great multi-threaded and gaming performance on a budget. Compatible with 600 and 700 series LGA1700 motherboards.',
    tags: ['Intel i5', '14th Gen', 'LGA1700', 'Budget'],
  },
  {
    id: 'mb-01',
    name: 'MSI MAG Z790 TOMAHAWK WIFI DDR5',
    category: 'motherboards',
    categoryName: 'MOTHERBOARD',
    brand: 'MSI',
    badge: 'TOP RATED',
    price: 118000,
    oldPrice: 125000,
    inStock: true,
    rating: 4.8,
    reviewsCount: 34,
    warranty: '3 Years Official Warranty',
    img: IMAGES.blueprint,
    specs: 'Intel LGA 1700 // DDR5 7200+ MHz (OC) // 4x M.2 Gen4 Slots // Wi-Fi 6E & 2.5G LAN // Audio Boost 5',
    description: 'Designed for Intel 12th, 13th & 14th Gen processors. Premium thermal solution with extended heatsink and M.2 Shield Frozr.',
    tags: ['Z790', 'DDR5', 'WiFi 6E', 'LGA1700'],
  },
  {
    id: 'mb-02',
    name: 'MSI PRO H610M-E DDR4 Motherboard',
    category: 'motherboards',
    categoryName: 'MOTHERBOARD',
    brand: 'MSI',
    badge: 'ENTRY LEVEL',
    price: 34500,
    oldPrice: 38000,
    inStock: true,
    rating: 4.5,
    reviewsCount: 47,
    warranty: '3 Years Official Warranty',
    img: IMAGES.blueprint,
    specs: 'LGA1700 // DDR4 Up to 3200MHz // 1x PCIe 4.0 x16 // 1x M.2 PCIe 3.0 // HDMI & VGA // Micro-ATX',
    description: 'Reliable entry-level LGA1700 motherboard with Core Boost and Memory Boost technologies for everyday stability.',
    tags: ['H610', 'DDR4', 'LGA1700', 'Micro-ATX'],
  },
  {
    id: 'mb-03',
    name: 'MSI B550M PRO-VDH WIFI AM4',
    category: 'motherboards',
    categoryName: 'MOTHERBOARD',
    brand: 'MSI',
    badge: 'POPULAR AM4',
    price: 51500,
    oldPrice: 56000,
    inStock: true,
    rating: 4.7,
    reviewsCount: 56,
    warranty: '3 Years Official Warranty',
    img: IMAGES.blueprint,
    specs: 'AMD AM4 // DDR4 Boost up to 4400MHz (OC) // Lightning Gen4 M.2 // Built-in Wi-Fi & Bluetooth',
    description: 'Top-selling AM4 motherboard for AMD Ryzen 3000, 4000, and 5000 series with integrated wireless and M.2 Shield Frozr.',
    tags: ['B550', 'AM4', 'WiFi', 'Ryzen'],
  },
  {
    id: 'cool-01',
    name: 'Arctic Liquid Freezer III 360 A-RGB Black Liquid Cooler',
    category: 'coolers',
    categoryName: 'COOLER & AIO',
    brand: 'Arctic',
    badge: 'PCPOINT CERTIFIED',
    price: 49500,
    oldPrice: 54000,
    inStock: true,
    rating: 5.0,
    reviewsCount: 82,
    warranty: '6 Years Arctic Manufacturer Warranty',
    img: IMAGES.media2,
    specs: '360mm Radiator // Dedicated VRM Fan // 3x P12 PWM A-RGB Fans // LGA1700 & AM5 Ready // Ultra Quiet',
    description: 'The award-winning Liquid Freezer III is engineered for peak cooling efficiency with extra thick 38mm radiator and dedicated VRM motherboard fan.',
    tags: ['Liquid Freezer III', '360mm AIO', 'A-RGB', 'LGA1700/AM5'],
  },
  {
    id: 'cool-02',
    name: 'Arctic Freezer 36 High-Performance Air Cooler',
    category: 'coolers',
    categoryName: 'COOLER & AIO',
    brand: 'Arctic',
    badge: 'SILENT WARRIOR',
    price: 17500,
    oldPrice: 19500,
    inStock: true,
    rating: 4.8,
    reviewsCount: 60,
    warranty: '6 Years Arctic Warranty',
    img: IMAGES.media2,
    specs: 'Push-Pull Dual P-Fans // Direct-Touch 4 Heatpipes // LGA1700 Contact Frame Included // 0dB Mode',
    description: 'Outstanding air cooling performance at an unbeatable price point. Features improved click-in fan mounting and Intel contact frame.',
    tags: ['Air Cooler', 'Push-Pull', 'Arctic', 'Silent'],
  },
  {
    id: 'cool-03',
    name: 'Thermaltake LA360-S ARGB Sync Liquid Cooler',
    category: 'coolers',
    categoryName: 'COOLER & AIO',
    brand: 'Thermaltake',
    badge: 'RGB SHOWCASE',
    price: 34000,
    oldPrice: 37500,
    inStock: true,
    rating: 4.6,
    reviewsCount: 31,
    warranty: '2 Years Official Warranty',
    img: IMAGES.media2,
    specs: '360mm Radiator // 3x 120mm High Static Pressure ARGB Fans // Copper Base Plate // Multi-Socket',
    description: 'Vibrant ARGB lighting paired with high thermal dissipation to keep high core count CPUs running at peak clocks.',
    tags: ['Thermaltake', '360mm AIO', 'ARGB', 'Water Cooler'],
  },
  {
    id: 'ssd-01',
    name: 'Samsung 990 PRO 2TB PCIe 4.0 NVMe M.2 SSD with Heatsink',
    category: 'storage',
    categoryName: 'STORAGE & SSD',
    brand: 'Samsung',
    badge: 'ULTRA SPEED',
    price: 88500,
    oldPrice: 96000,
    inStock: true,
    rating: 4.9,
    reviewsCount: 78,
    warranty: '5 Years Samsung Warranty',
    img: IMAGES.media1,
    specs: 'Read up to 7450 MB/s // Write up to 6900 MB/s // Integrated Heatsink // PS5 & PC Compatible',
    description: 'Reach maximum performance on PCIe 4.0. The smart thermal control delivers top power efficiency while maintaining ferocious speed.',
    tags: ['Samsung 990 Pro', '2TB SSD', '7450 MB/s', 'PCIe 4.0'],
  },
  {
    id: 'ssd-02',
    name: 'Crucial E100 1TB PCIe 4.0 NVMe M.2 SSD',
    category: 'storage',
    categoryName: 'STORAGE & SSD',
    brand: 'Crucial',
    badge: 'BEST SELLER',
    price: 56000,
    oldPrice: 62000,
    inStock: true,
    rating: 4.7,
    reviewsCount: 65,
    warranty: '3 Years Warranty',
    img: IMAGES.media1,
    specs: 'Read up to 5000 MB/s // Write up to 4200 MB/s // 3D NAND Technology // Compact 2280',
    description: 'Fast, reliable NVMe storage for gaming loads and snappy operating system responsiveness.',
    tags: ['Crucial', '1TB SSD', 'NVMe Gen4'],
  },
  {
    id: 'ssd-03',
    name: 'Addlink S70 512GB High Speed NVMe SSD',
    category: 'storage',
    categoryName: 'STORAGE & SSD',
    brand: 'Addlink',
    badge: 'FAST & BUDGET',
    price: 18500,
    oldPrice: 21000,
    inStock: true,
    rating: 4.6,
    reviewsCount: 43,
    warranty: '3 Years Official Warranty',
    img: IMAGES.media1,
    specs: 'Read 3400 MB/s // Write 2000 MB/s // 3D TLC NAND // LDPC ECC Engine',
    description: 'Exceptional read/write endurance and speed for gaming upgrades and system boot drives.',
    tags: ['Addlink', '512GB SSD', 'NVMe Gen3'],
  },
  {
    id: 'ram-01',
    name: 'Corsair Vengeance RGB 32GB (2x16GB) DDR5 6000MHz CL30',
    category: 'storage',
    categoryName: 'MEMORY & RAM',
    brand: 'Corsair',
    badge: 'ENHANCED EXPO/XMP',
    price: 52500,
    oldPrice: 58000,
    inStock: true,
    rating: 4.9,
    reviewsCount: 92,
    warranty: 'Lifetime Warranty',
    img: IMAGES.media1,
    specs: '32GB Kit (2x16GB) // DDR5-6000 // CL30 Low Latency // Intel XMP 3.0 & AMD EXPO // Dynamic Ten-Zone RGB',
    description: 'Deliver cutting-edge performance and frequencies tailored for high-end gaming and extreme multitasking workloads.',
    tags: ['Corsair', 'DDR5', '6000MHz', 'RGB RAM'],
  },
  {
    id: 'mon-01',
    name: 'ASUS ROG Swift OLED PG34WCDM 34" Curved Gaming Monitor',
    category: 'monitors',
    categoryName: 'MONITORS & DISPLAY',
    brand: 'Asus',
    badge: 'ULTRAWIDE OLED',
    price: 465000,
    oldPrice: 495000,
    inStock: true,
    rating: 5.0,
    reviewsCount: 22,
    warranty: '3 Years Asus Official Warranty',
    img: IMAGES.monitor,
    specs: '34" 800R Curved OLED // 3440 x 1440 UWQHD // 240Hz // 0.03ms GTG // Custom Heatsink // G-SYNC Compatible',
    description: 'Unmatched visual immersion. ROG 3rd-generation OLED technology offers deeper blacks, richer colors, and blistering 240Hz refresh rates.',
    tags: ['ROG Swift', 'OLED', '240Hz', '0.03ms', '34 inch'],
  },
  {
    id: 'mon-02',
    name: 'Predator 34-Inch Ultrawide Curved Gaming Monitor',
    category: 'monitors',
    categoryName: 'MONITORS & DISPLAY',
    brand: 'Asus',
    badge: 'ZERO DELAY',
    price: 295000,
    oldPrice: 320000,
    inStock: true,
    rating: 4.8,
    reviewsCount: 45,
    warranty: '3 Years Warranty',
    img: IMAGES.monitor,
    specs: '34" UWQHD 1440p // 180Hz // 1ms VRB // HDR400 // AMD FreeSync Premium // Ergonomic Stand',
    description: 'Expansive field of view with vibrant color accuracy and high refresh rate smooth motion.',
    tags: ['Ultrawide', '180Hz', 'HDR400', '1440p'],
  },
  {
    id: 'peri-01',
    name: 'Keychron Q1 Pro Custom Wireless Mechanical Keyboard',
    category: 'peripherals',
    categoryName: 'PERIPHERALS',
    brand: 'Keychron',
    badge: 'ENTHUSIAST TIER',
    price: 68000,
    oldPrice: 74000,
    inStock: true,
    rating: 4.9,
    reviewsCount: 57,
    warranty: '1 Year Warranty',
    img: IMAGES.media3,
    specs: 'Full CNC Aluminum Body // Hot-Swappable // QMK/VIA Programmable // Bluetooth 5.1 & Type-C // Gateron Jupiter Switches',
    description: 'All-metal wireless custom mechanical keyboard with double-gasket design and acoustic sound dampening pads.',
    tags: ['Keychron', 'Wireless Keyboard', 'Hot-Swap', 'Custom Mech'],
  },
  {
    id: 'peri-02',
    name: 'Razer Viper V3 Pro Ultra-Lightweight Wireless Gaming Mouse',
    category: 'peripherals',
    categoryName: 'PERIPHERALS',
    brand: 'Razer',
    badge: 'ESPORTS GOLD',
    price: 54000,
    oldPrice: 59000,
    inStock: true,
    rating: 4.9,
    reviewsCount: 84,
    warranty: '2 Years Razer Official Warranty',
    img: IMAGES.media3,
    specs: '54g Ultra-Lightweight // Focus Pro 35K Gen-2 Optical Sensor // 8000Hz HyperPolling // 95 Hours Battery',
    description: 'Engineered in collaboration with world-class esports pros to deliver true 8K wireless polling and surgical aim tracking.',
    tags: ['Razer', 'Wireless Mouse', '8000Hz', '54g Ultra-Light'],
  },
  {
    id: 'peri-03',
    name: 'Corsair HS80 RGB Wireless Gaming Headset with Dolby Atmos',
    category: 'peripherals',
    categoryName: 'PERIPHERALS',
    brand: 'Corsair',
    badge: 'SPATIAL AUDIO',
    price: 52000,
    oldPrice: 57000,
    inStock: true,
    rating: 4.7,
    reviewsCount: 39,
    warranty: '2 Years Corsair Warranty',
    img: IMAGES.media3,
    specs: 'Dolby Atmos Spatial Audio // Broadcast-Grade Omni Mic // 50mm Neodymium Drivers // 24-bit 96kHz High-Res',
    description: 'Immerse yourself in 3D spatial surround sound with hyper-fast Slipstream wireless technology and plush memory foam ear pads.',
    tags: ['Corsair', 'Wireless Headset', 'Dolby Atmos', 'Spatial Audio'],
  },
  {
    id: 'peri-04',
    name: 'MarsRhino Ergonomic Pro Gaming & Workstation Chair',
    category: 'peripherals',
    categoryName: 'PERIPHERALS',
    brand: 'MarsRhino',
    badge: 'COMFORT LEVEL 100',
    price: 89000,
    oldPrice: 98000,
    inStock: true,
    rating: 4.8,
    reviewsCount: 31,
    warranty: '2 Years Frame Warranty',
    img: IMAGES.pc,
    specs: 'High-Density Cold Cure Foam // 4D Adjustable Armrests // 165° Recline with Multi-Tilt // Class 4 Gas Lift',
    description: 'Engineered for extended gaming and intensive coding sessions with optimal lumbar and cervical spine support.',
    tags: ['Gaming Chair', 'MarsRhino', 'Ergonomic', '4D Armrests'],
  },
];

export const NAV_LINKS = [
  { label: 'All Products', href: '#products-section', category: 'all' },
  { label: 'Laptops', href: '#products-section', category: 'laptops' },
  { label: 'PC Components', href: '#products-section', category: 'gpus' },
  { label: 'Monitors & Display', href: '#products-section', category: 'monitors' },
  { label: 'Peripherals', href: '#products-section', category: 'peripherals' },
  { label: 'Build My PC', href: '#configurator', highlight: true },
];

export const TRUST_PILLARS = [
  {
    title: 'No.1 Warranty Support',
    desc: 'Sri Lanka’s premier user-friendly ticket system for real-time claim tracking.',
    icon: '🛡️',
  },
  {
    title: 'Koko 3x Installments',
    desc: 'Buy now and split your payments easily into 3 interest-free installments.',
    icon: '💳',
  },
  {
    title: 'Islandwide Express Delivery',
    desc: 'Fast, secure insured courier shipping directly to your doorstep in Sri Lanka.',
    icon: '🚀',
  },
  {
    title: 'Expert Rig Assembly',
    desc: 'Custom liquid loop and performance benchmark testing by seasoned PC builders.',
    icon: '⚡',
  },
];
